// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remaning_functionlity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remaning_functionlity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251349236_remaning_functionlity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
